# -*- coding: utf-8 -*-
"""Day4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1snQYIkMr1DWLYlccoJP3YfVBFFDfed1I
"""

#Final Project- Python based degree converter
celsius = int(input("Enter the temperature in Degree Celsius"))
fahrenheit = (celsius * 1.8) + 32
print("%.2f Celsius = %.2f Fahrenheit" %( celsius,fahrenheit ))